# Generated by Django 3.0.7 on 2020-06-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200610_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_category', to='orders.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
