# Generated by Django 3.0.7 on 2020-06-10 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200610_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subs', models.ManyToManyField(to='orders.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_menuitem', to='orders.MenuItem')),
                ('subs_extra', models.ManyToManyField(to='orders.Sub_Extra')),
                ('toppings', models.ManyToManyField(to='orders.Topping')),
            ],
        ),
    ]
