# Generated by Django 3.0.7 on 2020-06-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_sub_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='num_toppings',
            field=models.IntegerField(default=0),
        ),
    ]
