# Generated by Django 3.0.7 on 2020-06-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_menuitem_num_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_toppings', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem2_category', to='orders.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_toppings', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem1_category', to='orders.Category')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_menuitem2', to='orders.MenuItem2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem_menuitem1', to='orders.MenuItem1'),
        ),
        migrations.AlterField(
            model_name='sub_extra',
            name='subs',
            field=models.ManyToManyField(to='orders.MenuItem1'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
