# Generated by Django 3.0.7 on 2020-06-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200610_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item2',
        ),
        migrations.AddField(
            model_name='menuitem1',
            name='image',
            field=models.ImageField(default='/images/no_cameras.png', upload_to='images/upload'),
        ),
        migrations.AlterField(
            model_name='menuitem1',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='MenuItem2',
        ),
    ]
