# Generated by Django 3.0.7 on 2020-06-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200610_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem1',
            name='image',
            field=models.ImageField(default='no_cameras.png', upload_to='images/upload'),
        ),
    ]
