# Generated by Django 3.0.7 on 2020-06-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200610_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem1',
            name='image',
            field=models.ImageField(default='images/no-cameras.png', upload_to='images/upload'),
        ),
        migrations.AlterField(
            model_name='sub_extra',
            name='subs',
            field=models.ManyToManyField(related_name='subsextras', to='orders.MenuItem1'),
        ),
    ]
