# Generated by Django 3.0.7 on 2020-06-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200610_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem1',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
