# Generated by Django 3.0.7 on 2020-06-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200610_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem1',
            name='price_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
