# Generated by Django 3.0.7 on 2020-06-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200611_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subs_extra',
            field=models.ManyToManyField(blank='True', related_name='cartitem_subsextras', to='orders.Sub_Extra'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='toppings',
            field=models.ManyToManyField(blank='True', related_name='cartitem_toppings', to='orders.Topping'),
        ),
    ]
