# Generated by Django 3.0.7 on 2020-06-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200613_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank='True', decimal_places=2, max_digits=10),
        ),
    ]
